#!/usr/bin/env python3
"""Generate unicode -> GB2312 lookup table header using Python's built-in codec."""
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "firmware" / "src" / "ui" / "gb2312_table.h"

pairs = []
for hi in range(0xA1, 0x100):
    for lo in range(0xA1, 0x100):
        if lo == 0x7F:
            continue
        try:
            ch = bytes([hi, lo]).decode("gb2312")
        except (UnicodeDecodeError, ValueError):
            continue
        pairs.append((ord(ch), (hi << 8) | lo))

pairs.sort(key=lambda p: p[0])

lines = [
    "// Generated by scripts/gen_gb2312_table.py — do not edit by hand.",
    "#pragma once",
    "#include <cstdint>",
    "",
    f"// {len(pairs)} entries, sorted by unicode codepoint.",
    f"constexpr uint16_t kGbCp[{len(pairs)}] = {{",
]
for i in range(0, len(pairs), 8):
    lines.append("    " + ", ".join(f"0x{p[0]:04X}" for p in pairs[i:i+8]) + ",")
lines += ["};", "", f"constexpr uint16_t kGbGb[{len(pairs)}] = {{"]
for i in range(0, len(pairs), 8):
    lines.append("    " + ", ".join(f"0x{p[1]:04X}" for p in pairs[i:i+8]) + ",")
lines += ["};", "", f"constexpr int kGbCount = {len(pairs)};", ""]

lines += [
    "// 二分查找；未命中返回 0。ASCII(0x20-0x7E) 直接透传，不走此表。",
    "inline uint16_t unicode_to_gb2312(uint16_t cp) {",
    "    int lo = 0, hi = kGbCount - 1;",
    "    while (lo <= hi) {",
    "        int mid = (lo + hi) / 2;",
    "        if (kGbCp[mid] == cp) return kGbGb[mid];",
    "        if (kGbCp[mid] < cp) lo = mid + 1; else hi = mid - 1;",
    "    }",
    "    return 0;",
    "}",
    "",
]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({len(pairs)} entries)")
