#!/usr/bin/env python3
"""Generate the multi-frame pixel-cat header (cat_frames.h) from sprite strips.

Source asset: "pixel-art-cat-doing-some-stuff" by (opengameart)
  https://opengameart.org/content/pixel-art-cat-doing-some-stuff
License: CC-BY 3.0 (attribution required).

Download the four strips into a directory (e.g. assets/cat_source/) then run:
    python3 scripts/gen_cat_frames.py assets/cat_source

Files (opengameart.org/sites/default/files/...):
    spr_pc_walk_strip4.png   152x43  -> 4 walk frames  (38x43 each)
    spr_pc_beat_strip8.png   680x54  -> 8 beat frames  (85x54 each)
    spr_pc_jump_strip2_0.png  72x48  -> 2 jump frames  (36x48 each)
    spr_pc_die_strip2.png     82x38  -> 2 die frames   (41x38 each)

Output: firmware/src/ui/cat_frames.h
  - frames normalized to a common WxH canvas (bottom-aligned, center-x)
  - kFrameW/kFrameH, kFrameCount, kFrameOffset[], kFrameRGB[] (RGB565), kFrameMask[] (1-bit)
  - animation layout: walk[0..3], beat[4..11], jump[12..13], die[14..15]
"""
from PIL import Image
import sys
from pathlib import Path

SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("assets/cat_source")
OUT = Path(__file__).resolve().parent.parent / "firmware" / "src" / "ui" / "cat_frames.h"

STRIPS = [
    ("spr_pc_walk_strip4.png",   4, 38, 43),
    ("spr_pc_beat_strip8.png",   8, 85, 54),
    ("spr_pc_jump_strip2_0.png", 2, 36, 48),
    ("spr_pc_die_strip2.png",    2, 41, 38),
]


def slices(path, n, w, h):
    im = Image.open(SRC / path).convert("RGBA")
    out = []
    for i in range(n):
        fr = im.crop((i * w, 0, i * w + w, h))
        b = fr.getbbox()
        if b:
            fr = fr.crop(b)
        out.append(fr)
    return out


frames = []
for name, n, w, h in STRIPS:
    frames += slices(name, n, w, h)

maxW = max(f.width for f in frames)
maxH = max(f.height for f in frames)

canvases = []
for f in frames:
    c = Image.new("RGBA", (maxW, maxH), (0, 0, 0, 0))
    c.paste(f, ((maxW - f.width) // 2, maxH - f.height), f)  # bottom-align
    canvases.append(c)

W, H = maxW, maxH
rgb = []
mask_bits = []
for c in canvases:
    a = c.getchannel("A")
    for y in range(H):
        for x in range(W):
            px = c.getpixel((x, y))
            opaque = a.getpixel((x, y)) > 32
            mask_bits.append(1 if opaque else 0)
            if opaque:
                r, g, b = px[0], px[1], px[2]
                rgb.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
            else:
                rgb.append(0)

mask_bytes = []
bits_per = W * H
for i in range(len(frames)):
    bits = mask_bits[i * bits_per:(i + 1) * bits_per]
    while len(bits) % 8:
        bits.append(0)
    for j in range(0, len(bits), 8):
        b = 0
        for k in range(8):
            b = (b << 1) | bits[j + k]
        mask_bytes.append(b)

lines = [
    "// Generated by scripts/gen_cat_frames.py — do not edit by hand.",
    "// Source: opengameart.org/content/pixel-art-cat-doing-some-stuff (CC-BY 3.0)",
    "#pragma once", "#include <cstdint>", "",
    f"constexpr int16_t kFrameW = {W};",
    f"constexpr int16_t kFrameH = {H};",
    f"constexpr int kFrameCount = {len(frames)};",
    "",
    f"constexpr uint32_t kFrameOffset[{len(frames)}] = {{",
]
offsets = [i * W * H for i in range(len(frames))]
for i in range(0, len(offsets), 8):
    lines.append("    " + ", ".join(str(o) for o in offsets[i:i + 8]) + ",")
lines += ["};", "", f"constexpr uint16_t kFrameRGB[{len(rgb)}] = {{"]
for i in range(0, len(rgb), 12):
    lines.append("    " + ", ".join(f"0x{v:04X}" for v in rgb[i:i + 12]) + ",")
lines += ["};", "", f"constexpr uint8_t kFrameMask[{len(mask_bytes)}] = {{"]
for i in range(0, len(mask_bytes), 16):
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in mask_bytes[i:i + 16]) + ",")
lines += ["};", ""]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({len(frames)} frames, {W}x{H}, {len(rgb)} rgb, {len(mask_bytes)} mask bytes)")
