#!/usr/bin/env python3
"""Generate the 96x96 orange-white cat sprite header from the 🐈 emoji."""
from playwright.sync_api import sync_playwright
from PIL import Image
import io
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "firmware" / "src" / "ui" / "cat_sprite.h"
CHROMIUM = None
import glob, os
for p in sorted(glob.glob(os.path.expanduser("~/Library/Caches/ms-playwright/chromium_headless_shell-*/chrome-headless-shell-mac-x64/chrome-headless-shell")), reverse=True):
    CHROMIUM = p
    break
if not CHROMIUM:
    raise SystemExit("chromium headless shell not found; run: playwright install")

# orange + white (no pink)
PAL = [(0x40, 0x2a, 0x1c), (0xf6, 0xc8, 0x80), (0xd6, 0x9c, 0x58), (0xfc, 0xe2, 0xb4)]
SIZE = 96

def render(size=1024):
    html = f'''<html><head><meta charset="utf-8"></head>
    <body style="margin:0;background:transparent;display:flex;align-items:center;justify-content:center;width:{size}px;height:{size}px;overflow:hidden;">
    <span style="font-family:'Apple Color Emoji','Segoe UI Emoji','Noto Color Emoji',sans-serif;font-size:{int(size*0.92)}px;line-height:1;">🐈</span></body></html>'''
    with sync_playwright() as p:
        b = p.chromium.launch(executable_path=CHROMIUM, args=["--force-color-profile=srgb"])
        pg = b.new_page(viewport={"width": size, "height": size})
        pg.set_content(html); pg.wait_for_timeout(350)
        buf = pg.screenshot(omit_background=True); b.close()
    return Image.open(io.BytesIO(buf)).convert("RGBA")

def nearest(c):
    r, g, b = c
    best, bestd = PAL[0], 1e9
    for p in PAL:
        d = (r-p[0])**2 + (g-p[1])**2 + (b-p[2])**2
        if d < bestd: best, bestd = p, d
    return best

img = render().resize((SIZE, SIZE), Image.LANCZOS)
a = img.getchannel("A")
mask_bits = []
rgbs = []
for y in range(SIZE):
    for x in range(SIZE):
        opaque = a.getpixel((x, y)) > 48
        mask_bits.append(1 if opaque else 0)
        if opaque:
            r, g, b = nearest(img.getpixel((x, y))[:3])
            rgbs.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
        else:
            rgbs.append(0)

mask_bytes = []
for i in range(0, len(mask_bits), 8):
    byte = 0
    for j in range(8):
        byte = (byte << 1) | mask_bits[i + j]
    mask_bytes.append(byte)

lines = ["// Generated by scripts/gen_cat_sprite.py — do not edit by hand.",
         "#pragma once", "#include <cstdint>", "",
         f"// {SIZE}x{SIZE} orange-white cat sprite (RGB565) + 1-bit alpha mask.",
         f"constexpr int kCatSpriteW = {SIZE};",
         f"constexpr int kCatSpriteH = {SIZE};", "",
         f"constexpr uint16_t kCatSprite[{len(rgbs)}] = {{"]
for i in range(0, len(rgbs), 12):
    lines.append("    " + ", ".join(f"0x{v:04X}" for v in rgbs[i:i+12]) + ",")
lines += ["};", "", f"constexpr uint8_t kCatMask[{len(mask_bytes)}] = {{"]
for i in range(0, len(mask_bytes), 16):
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in mask_bytes[i:i+16]) + ",")
lines += ["};", ""]

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({len(rgbs)} px, {len(mask_bytes)} mask bytes)")
